# Generated by Django 5.2.16 on 2026-07-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('feed_url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('lead', models.TextField(blank=True)),
                ('first_paragraph', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('language', models.CharField(default='ro', max_length=10)),
                ('content_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('pending', 'În așteptare'), ('processed', 'Procesat'), ('failed', 'Eșuat')], db_index=True, default='pending', max_length=20)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('primary_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='taxonomy.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.source')),
            ],
            options={
                'ordering': ('-published_at', '-collected_at'),
            },
        ),
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('is_manual', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_matches', to='news.article')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_matches', to='taxonomy.topic')),
            ],
            options={
                'ordering': ('-score',),
                'constraints': [models.UniqueConstraint(fields=('article', 'topic'), name='unique_article_topic_match')],
            },
        ),
    ]
