# Generated by Django 5.2.16 on 2026-07-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Articolul reprezentativ pentru acelasi eveniment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_articles', to='news.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='duplicate_score',
            field=models.FloatField(default=0),
        ),
    ]
