# Generated by Django 5.2.16 on 2026-07-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_duplicate_of_article_duplicate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='second_paragraph',
            field=models.TextField(blank=True),
        ),
    ]
