# Generated by Django 5.2.16 on 2026-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_second_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
