# Generated by Django 5.2.16 on 2026-07-30 19:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_aiusage_refreshrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticUpdateLock',
            fields=[
                ('name', models.CharField(default='automatic_news_update', max_length=50, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('status', models.CharField(choices=[('candidate', 'Candidat'), ('pending', 'În așteptare'), ('generated', 'Generat'), ('indexable', 'Indexabil'), ('stable', 'Stabil'), ('budget_blocked', 'Blocat de buget'), ('failed', 'Eșuat')], db_index=True, default='candidate', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('confirmed_facts', models.JSONField(blank=True, default=list)),
                ('differences', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('source_snapshot', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_article_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_generated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_generation_at', models.DateTimeField(blank=True, null=True)),
                ('generated_source_count', models.PositiveIntegerField(default=0)),
                ('generation_count', models.PositiveIntegerField(default=0)),
                ('initial_cost_gbp', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('update_cost_gbp', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('total_cost_gbp', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-last_article_at', '-first_seen_at'),
            },
        ),
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=True)),
                ('max_new_events_per_day', models.PositiveIntegerField(default=100)),
                ('max_new_events_per_month', models.PositiveIntegerField(default=2000)),
                ('max_cost_gbp_per_day', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10)),
                ('max_cost_gbp_per_month', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10)),
                ('max_cost_gbp_per_event', models.DecimalField(decimal_places=3, default=Decimal('0.025'), max_digits=10)),
                ('minimum_sources_for_creation', models.PositiveSmallIntegerField(default=2)),
                ('minimum_sources_for_indexing', models.PositiveSmallIntegerField(default=3)),
                ('reserved_cost_gbp', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buget evenimente',
                'verbose_name_plural': 'Buget evenimente',
            },
        ),
        migrations.AddField(
            model_name='aiusage',
            name='usage_type',
            field=models.CharField(choices=[('article_classification', 'Clasificare articol'), ('event_claim_extraction', 'Extragere afirmații'), ('event_summary', 'Sinteză eveniment'), ('event_update', 'Actualizare eveniment')], db_index=True, default='article_classification', max_length=40),
        ),
        migrations.AddField(
            model_name='refreshrun',
            name='classification_cost_gbp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='refreshrun',
            name='event_cost_gbp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='refreshrun',
            name='events_budget_blocked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refreshrun',
            name='events_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refreshrun',
            name='events_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refreshrun',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automat')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to='news.event'),
        ),
        migrations.CreateModel(
            name='EventArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_membership', to='news.article')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_articles', to='news.event')),
            ],
            options={
                'ordering': ('added_at',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='articles',
            field=models.ManyToManyField(related_name='events', through='news.EventArticle', to='news.article'),
        ),
    ]
