# Generated by Django 5.2.16 on 2026-07-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_automaticupdatelock_event_eventbudget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAIUsage',
            fields=[
            ],
            options={
                'verbose_name': 'Consum AI eveniment',
                'verbose_name_plural': 'Consum AI evenimente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.aiusage',),
        ),
    ]
