"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool("DJANGO_DEBUG", False)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if DEBUG and not SECRET_KEY:
    SECRET_KEY = "django-insecure-newsflow-local-development-only"

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost" if DEBUG else ""
)
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'taxonomy',
    'news',
    'recommendations',
]

UNFOLD = {
    "SITE_TITLE": "Newsflow Admin",
    "SITE_HEADER": "Newsflow.ro",
    "SITE_SUBHEADER": "Analytics & operations",
    "DASHBOARD_CALLBACK": "config.admin_dashboard.dashboard_callback",
    "STYLES": [lambda request: f"{STATIC_URL}css/admin-dashboard.css"],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'recommendations.context_processors.saved_news_count',
                'recommendations.context_processors.navigation_categories',
                'recommendations.context_processors.latest_news_refresh',
                'recommendations.context_processors.analytics_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ro'

TIME_ZONE = os.getenv("TIME_ZONE", "Europe/Bucharest")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'feed'
LOGOUT_REDIRECT_URL = 'feed'

AUTH_USER_MODEL = 'accounts.User'

NEWSFLOW_USER_AGENT = 'Newsflow/1.0 (+local-development)'
NEWSFLOW_REQUEST_TIMEOUT = 10
NEWSFLOW_CONNECT_TIMEOUT = float(os.getenv("NEWSFLOW_CONNECT_TIMEOUT", "5"))
NEWSFLOW_READ_TIMEOUT = float(os.getenv("NEWSFLOW_READ_TIMEOUT", "10"))
NEWSFLOW_MAX_FEED_BYTES = int(
    os.getenv("NEWSFLOW_MAX_FEED_BYTES", str(5 * 1024 * 1024))
)
NEWSFLOW_MAX_PAGE_BYTES = int(
    os.getenv("NEWSFLOW_MAX_PAGE_BYTES", str(3 * 1024 * 1024))
)
NEWSFLOW_MAX_IMAGE_BYTES = int(
    os.getenv("NEWSFLOW_MAX_IMAGE_BYTES", str(3 * 1024 * 1024))
)
NEWSFLOW_MAX_ENTRIES_PER_SOURCE = 15

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() in {"1", "true", "yes"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() in {"1", "true", "yes"}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Newsflow <no-reply@localhost>")
APP_PUBLIC_URL = os.getenv("APP_PUBLIC_URL", "http://127.0.0.1:8000")
PUBLIC_CONTACT_EMAIL = os.getenv("PUBLIC_CONTACT_EMAIL", "").strip()
GOOGLE_ANALYTICS_ID = os.getenv("GOOGLE_ANALYTICS_ID", "G-DDT1Z5SD9L").strip()

# Production defaults are secure. Set DJANGO_DEBUG=true only for local development.
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", True)
    CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", True)
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", True
    )
    SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", True)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
TWO_FACTOR_TOKEN_TTL_MINUTES = 15
TWO_FACTOR_RESEND_COOLDOWN_SECONDS = 60
TWO_FACTOR_MAX_SENDS_PER_HOUR = 5

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_CLASSIFICATION_ENABLED = os.getenv(
    "OPENAI_CLASSIFICATION_ENABLED", "true"
).lower() in {"1", "true", "yes"}
OPENAI_CLASSIFICATION_MODEL = os.getenv(
    "OPENAI_CLASSIFICATION_MODEL", "gpt-5.4-nano"
)
OPENAI_INPUT_USD_PER_MILLION = os.getenv("OPENAI_INPUT_USD_PER_MILLION", "0.20")
OPENAI_CACHED_INPUT_USD_PER_MILLION = os.getenv(
    "OPENAI_CACHED_INPUT_USD_PER_MILLION", "0.02"
)
OPENAI_OUTPUT_USD_PER_MILLION = os.getenv("OPENAI_OUTPUT_USD_PER_MILLION", "1.25")
OPENAI_USD_TO_GBP_RATE = os.getenv("OPENAI_USD_TO_GBP_RATE", "0.7525")
OPENAI_CLASSIFICATION_AUTO_THRESHOLD = float(
    os.getenv("OPENAI_CLASSIFICATION_AUTO_THRESHOLD", "0.80")
)
OPENAI_EVENT_EXTRACTION_MODEL = os.getenv(
    "OPENAI_EVENT_EXTRACTION_MODEL", "gpt-5.4-nano"
)
OPENAI_EVENT_SUMMARY_MODEL = os.getenv(
    "OPENAI_EVENT_SUMMARY_MODEL", "gpt-5.4-mini"
)
OPENAI_EVENT_NANO_INPUT_USD_PER_MILLION = os.getenv(
    "OPENAI_EVENT_NANO_INPUT_USD_PER_MILLION", "0.20"
)
OPENAI_EVENT_NANO_CACHED_INPUT_USD_PER_MILLION = os.getenv(
    "OPENAI_EVENT_NANO_CACHED_INPUT_USD_PER_MILLION", "0.02"
)
OPENAI_EVENT_NANO_OUTPUT_USD_PER_MILLION = os.getenv(
    "OPENAI_EVENT_NANO_OUTPUT_USD_PER_MILLION", "1.25"
)
OPENAI_EVENT_MINI_INPUT_USD_PER_MILLION = os.getenv(
    "OPENAI_EVENT_MINI_INPUT_USD_PER_MILLION", "0.75"
)
OPENAI_EVENT_MINI_CACHED_INPUT_USD_PER_MILLION = os.getenv(
    "OPENAI_EVENT_MINI_CACHED_INPUT_USD_PER_MILLION", "0.075"
)
OPENAI_EVENT_MINI_OUTPUT_USD_PER_MILLION = os.getenv(
    "OPENAI_EVENT_MINI_OUTPUT_USD_PER_MILLION", "4.50"
)
NEWSFLOW_EVENT_ACTIVE_DAYS = int(os.getenv("NEWSFLOW_EVENT_ACTIVE_DAYS", "7"))
NEWSFLOW_EVENT_REGENERATION_MINUTES = int(
    os.getenv("NEWSFLOW_EVENT_REGENERATION_MINUTES", "60")
)
NEWSFLOW_EVENT_ESTIMATED_RESERVATION_GBP = os.getenv(
    "NEWSFLOW_EVENT_ESTIMATED_RESERVATION_GBP", "0.010"
)
NEWSFLOW_AUTOMATIC_LOCK_TIMEOUT_MINUTES = int(
    os.getenv("NEWSFLOW_AUTOMATIC_LOCK_TIMEOUT_MINUTES", "120")
)
NEWSFLOW_EVENT_EXCLUDED_SOURCE_SLUGS = env_list(
    "NEWSFLOW_EVENT_EXCLUDED_SOURCE_SLUGS", "gandul"
)

if not DEBUG:
    required = {
        "DJANGO_SECRET_KEY": SECRET_KEY,
        "DJANGO_ALLOWED_HOSTS": ALLOWED_HOSTS,
        "DJANGO_CSRF_TRUSTED_ORIGINS": CSRF_TRUSTED_ORIGINS,
        "APP_PUBLIC_URL": APP_PUBLIC_URL.startswith("https://"),
        "PUBLIC_CONTACT_EMAIL": PUBLIC_CONTACT_EMAIL,
        "EMAIL_BACKEND": EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend",
        "EMAIL_HOST": EMAIL_HOST,
        "EMAIL_HOST_USER": EMAIL_HOST_USER,
        "EMAIL_HOST_PASSWORD": EMAIL_HOST_PASSWORD,
    }
    missing = [name for name, value in required.items() if not value]
    if missing:
        raise ImproperlyConfigured(
            "Configurație de producție incompletă: " + ", ".join(missing)
        )

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
